### ISSUE TITLE
✨ Administration Area

### ISSUE THREAD

**Issue by AlexanderEDavis** [luketainton/FHeD#116]
**Is your feature request related to a problem? Please describe.**
Admins need to be able to view, open, close, assign and update tickets

**Describe the solution you'd like**
A dashboard similar to the main app designed for admins. Possible in /admin/

**Describe alternatives you've considered**
Admins access the ticket in phpnyadmin

**Comment by AlexanderEDavis** [comment]
@luketainton how do we know the user is admin? I can't find anything in the db. Is it set in Keycloak?

**Comment by luketainton** [comment]
Right now there's nothing to dictate their role - we could have Keycloak push it down through roles, which is probably better than storing it in a db

**Comment by AlexanderEDavis** [comment]
What if we had keycloak push it down then it gets stored/updated in the DB upon login? That would make the code i have just written work

**Comment by luketainton** [comment]
> What if we had keycloak push it down then it gets stored/updated in the DB upon login? That would make the code i have just written work

Keycloak is now configured to push an attribute called `roles`, which will be set to either `admin`, `agent`, or `user` depending on the desired functionality for the user.

**Comment by AlexanderEDavis** [comment]
> > What if we had keycloak push it down then it gets stored/updated in the DB upon login? That would make the code i have just written work
> 
> Keycloak is now configured to push an attribute called `roles`, which will be set to either `admin`, `agent`, or `user` depending on the desired functionality for the user.

I will update the db(s) and creation script. Then update my code accordingly. Also, I was thinking admin and agent are the same thing?

**Comment by luketainton** [comment]
OK, I'll remove `admin`. The functions in app_functions.php also need to be updated to a) get the role from KC, and b) save it in the session
