### ISSUE TITLE
Attachments with spaces in name don't download correctly

### ISSUE THREAD

**Issue by luketainton** [luketainton/FHeD#78]
**Describe the bug**
When trying to download a file with spaces in the name, the downloaded file's name stops at the first space, which cuts off the file extension.

**To Reproduce**
1. Go to any request with attachments
2. Click on the attachment with spaces in the name
3. See error

**Expected behavior**
The downloaded file should have the full file name and extension.

**Screenshots**
<img width="1680" alt="Screenshot 2020-08-13 at 15 42 14" src="https://user-images.githubusercontent.com/22561713/90148941-d3a8ea80-dd7b-11ea-8898-022599ada8a6.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.0 Big Sur Beta
 - Browser: Firefox Developer Edition
 - Version: 80.0b7

**Comment by AlexanderEDavis** [comment]
This is only an issue with Firefox. Tested with Chrome, Edge (legacy), Firefox and Edge (new)

**Comment by AlexanderEDavis** [comment]
Issue caused by https://thisinterestsme.com/firefox-downloads-files-without-extension/

Resolution being created now
