### ISSUE TITLE
🐛 Version not automatically updated in program

### ISSUE THREAD

**Issue by AlexanderEDavis** [luketainton/FHeD#95]
**Describe the bug**
The footer shows the version number of FHeD. This should be automatically updated when the package is created and incremented each time (e.g. we should be on v0.1.23 etc)

**To Reproduce**
1. Go to homepage
2. See error

**Expected behavior**
Version number should be automatically updated when the package is created/updated and incremented each time (e.g. we should be on v0.1.23 etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/9097891/90289664-44333280-de74-11ea-86e1-1777d790eaf0.png)

**Comment by luketainton** [comment]
Is there a way to automate this?

(Also, the sub button needs to be on the same line but aligned to the right - any ideas?)

**Comment by AlexanderEDavis** [comment]
> Is there a way to automate this?
> 
> (Also, the sub button needs to be on the same line but aligned to the right - any ideas?)

Not 100% sure about automation. I think there is but unsure as not a native with docker.

Sub button style= "float: right"?

**Comment by luketainton** [comment]
I'll look into automatic versioning - I didn't want to start counting versions until we get to a "stable" release.

Not anymore :)

**Comment by AlexanderEDavis** [comment]
> I'll look into automatic versioning - I didn't want to start counting versions until we get to a "stable" release.
> 
> Not anymore :)

https://medium.com/better-programming/how-to-version-your-docker-images-1d5c577ebf54

**Comment by AlexanderEDavis** [comment]
https://github.com/marketplace/actions/create-new-semantic-version
