### ISSUE TITLE
🐛 Subscribe button does not work

### ISSUE THREAD

**Issue by AlexanderEDavis** [luketainton/FHeD#96]
**Describe the bug**
When you click on subscribe in the footer it displays an error

**To Reproduce**
1. Go to homepage
2. Click on Subscribe
3. See error

**Expected behavior**
Form to be displayed allowing user to subscribe to mailing list

**Screenshots**
![image](https://user-images.githubusercontent.com/9097891/90289784-82c8ed00-de74-11ea-83b0-5712c0724894.png)

**Comment by luketainton** [comment]
I already know what the problem is here, will push a fix soon.
